// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDg2VkYGgKN_lDVJX6GWMSbJqAwnMIv61Y',
    appId: '1:791880206926:web:145646f48ef9b2d8d4511f',
    messagingSenderId: '791880206926',
    projectId: 'instascan-aa2fc',
    authDomain: 'instascan-aa2fc.firebaseapp.com',
    databaseURL: 'https://instascan-aa2fc-default-rtdb.firebaseio.com',
    storageBucket: 'instascan-aa2fc.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjuCJIlakai7ZOKStg09rnnIyruKyy2Ys',
    appId: '1:791880206926:android:da105cfb65b91acad4511f',
    messagingSenderId: '791880206926',
    projectId: 'instascan-aa2fc',
    databaseURL: 'https://instascan-aa2fc-default-rtdb.firebaseio.com',
    storageBucket: 'instascan-aa2fc.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFP1esMycIW8QPHl1MdbpDyeB5rmvbxVU',
    appId: '1:791880206926:ios:3012885ab85ede4dd4511f',
    messagingSenderId: '791880206926',
    projectId: 'instascan-aa2fc',
    databaseURL: 'https://instascan-aa2fc-default-rtdb.firebaseio.com',
    storageBucket: 'instascan-aa2fc.firebasestorage.app',
    iosBundleId: 'com.example.instascan',
  );
}
